import type { NextPage } from 'next'
import Head from 'next/head'

const CreateItem: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Item - NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Create a new item</h1>
    </>
  )
}

export default CreateItem
