import type { NextPage } from 'next'
import Head from 'next/head'

const MyAssets: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Assets - NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>My NFT Assets</h1>
    </>
  )
}

export default MyAssets
